package:
  name: vcf2db
  version: '2017.07.31'

build:
  number: 0
  skip: True # [not py27]
 
source:
  fn: vcf2db-7594ced.tar.gz
  url: https://github.com/quinlan-lab/vcf2db/archive/7594ced.tar.gz
  sha256: a59afe09cf833961513514de702b6c09779971b60108056dc9e8526400feb8c4

requirements:
  build:
    - python
    - perl
    - nomkl # [unix]
    - cffi
    - snappy
    - python-snappy
    - sqlalchemy
    - cyvcf2
    - numpy
    - peddy >=0.2.9
    - geneimpacts >0.2.0
  run:
    - python
    - nomkl # [unix]
    - cffi
    - snappy
    - python-snappy
    - sqlalchemy
    - cyvcf2
    - numpy
    - peddy >=0.2.9
    - geneimpacts >0.2.0

test:
  commands:
    - vcf2db.py -h

about:
  home: https://github.com/quinlan-lab/vcf2db
  license: MIT
  summary: Create a gemini-compatible database from a VCF
